### ISSUE TITLE
Issue with NSRL lookup & Option Filters

### ISSUE THREAD

**Issue by vxtx** [keithjjones/fileintel#3]
user@linux:~/gitprojects/fileintel$ python fileintel.py --virustotal  myconfig.conf sampledata/smallerlist.txt -a > myoutout.csv
INFO:  Using 7Zip from: /usr/bin/p7zip
Preprocessing NSRL database.... please hold...
Traceback (most recent call last):
  File "fileintel.py", line 161, in <module>
    NSRLHashes = NSRL.lookup(filehashes, SevenZipPath)
  File "/home/user/gitprojects/fileintel/libs/nsrl.py", line 79, in lookup
    outputhashes = self.searchhashes(csvIn, upperhashes)
  File "/home/user/gitprojects/fileintel/libs/nsrl.py", line 100, in searchhashes
    elif row[1].upper() in upperhashes:
IndexError: list index out of range

I used --virustotal / -v option however, couldn't stop NSRL lookups. Also the lookups fail, with above err.

Tx

**Comment by keithjjones** [comment]
NSRL lookups happen all the time, I think.  It's been about a year since I looked at this code.

**Comment by keithjjones** [comment]
Is this still an error?  I'm going to close.  Reopen if it's still an error.
