### ISSUE TITLE
nsrl download link is broken

### ISSUE THREAD

**Issue by Robomikel** [keithjjones/fileintel#6]
Hey Kieth, 
 
 Just wanted to let you know the download link  leads to a NIST "oops, no longer exists" page. I think this is the new one. Let me know if I am wrong. Just did a quick search its going to take some time to download. 

https://www.nist.gov/itl/ssd/software-quality-group/national-software-reference-library-nsrl/nsrl-download/current-rds

- Michael

**Comment by keithjjones** [comment]
Fixed, thanks!
